package com.neusoft.designer.service.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpObjAttrType;
import com.neusoft.designer.service.domain.HpObjAttrTypeExample;

public interface HpObjAttrTypeMapper extends GenDao {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTR_TYPE
     *
     * @mbg.generated
     */
    long countByExample(HpObjAttrTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTR_TYPE
     *
     * @mbg.generated
     */
    int deleteByExample(HpObjAttrTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTR_TYPE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTR_TYPE
     *
     * @mbg.generated
     */
    int insert(HpObjAttrType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTR_TYPE
     *
     * @mbg.generated
     */
    int insertSelective(HpObjAttrType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTR_TYPE
     *
     * @mbg.generated
     */
    List<HpObjAttrType> selectByExample(HpObjAttrTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTR_TYPE
     *
     * @mbg.generated
     */
    HpObjAttrType selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTR_TYPE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpObjAttrType record, @Param("example") HpObjAttrTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTR_TYPE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpObjAttrType record, @Param("example") HpObjAttrTypeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTR_TYPE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpObjAttrType record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTR_TYPE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpObjAttrType record);
}
