package com.neusoft.designer.service.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpObjORG;
import com.neusoft.designer.service.domain.HpObjORGExample;

public interface HpObjORGMapper extends GenDao {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ORG
     *
     * @mbg.generated
     */
    long countByExample(HpObjORGExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ORG
     *
     * @mbg.generated
     */
    int deleteByExample(HpObjORGExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ORG
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ORG
     *
     * @mbg.generated
     */
    int insert(HpObjORG record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ORG
     *
     * @mbg.generated
     */
    int insertSelective(HpObjORG record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ORG
     *
     * @mbg.generated
     */
    List<HpObjORG> selectByExample(HpObjORGExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ORG
     *
     * @mbg.generated
     */
    HpObjORG selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ORG
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpObjORG record, @Param("example") HpObjORGExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ORG
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpObjORG record, @Param("example") HpObjORGExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ORG
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpObjORG record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ORG
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpObjORG record);
}
