package com.neusoft.designer.service.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpObjEnum;
import com.neusoft.designer.service.domain.HpObjEnumExample;

public interface HpObjEnumMapper extends GenDao {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM
     *
     * @mbg.generated
     */
    long countByExample(HpObjEnumExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM
     *
     * @mbg.generated
     */
    int deleteByExample(HpObjEnumExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM
     *
     * @mbg.generated
     */
    int insert(HpObjEnum record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM
     *
     * @mbg.generated
     */
    int insertSelective(HpObjEnum record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM
     *
     * @mbg.generated
     */
    List<HpObjEnum> selectByExample(HpObjEnumExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM
     *
     * @mbg.generated
     */
    HpObjEnum selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpObjEnum record, @Param("example") HpObjEnumExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpObjEnum record, @Param("example") HpObjEnumExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpObjEnum record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpObjEnum record);
}
