package com.neusoft.designer.service.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpObjEnumValue;
import com.neusoft.designer.service.domain.HpObjEnumValueExample;

public interface HpObjEnumValueMapper extends GenDao {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    long countByExample(HpObjEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int deleteByExample(HpObjEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int insert(HpObjEnumValue record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int insertSelective(HpObjEnumValue record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    List<HpObjEnumValue> selectByExample(HpObjEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    HpObjEnumValue selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpObjEnumValue record,
                                 @Param("example") HpObjEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpObjEnumValue record, @Param("example") HpObjEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpObjEnumValue record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpObjEnumValue record);
}
