package com.neusoft.designer.service.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpObjAttribute;
import com.neusoft.designer.service.domain.HpObjAttributeExample;

public interface HpObjAttributeMapper extends GenDao {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    long countByExample(HpObjAttributeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int deleteByExample(HpObjAttributeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int insert(HpObjAttribute record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int insertSelective(HpObjAttribute record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    List<HpObjAttribute> selectByExample(HpObjAttributeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    HpObjAttribute selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpObjAttribute record,
                                 @Param("example") HpObjAttributeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpObjAttribute record, @Param("example") HpObjAttributeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpObjAttribute record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpObjAttribute record);
}
