package com.neusoft.designer.service.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpObjLayout;
import com.neusoft.designer.service.domain.HpObjLayoutExample;

public interface HpObjLayoutMapper extends GenDao {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    long countByExample(HpObjLayoutExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int deleteByExample(HpObjLayoutExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int insert(HpObjLayout record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int insertSelective(HpObjLayout record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    List<HpObjLayout> selectByExample(HpObjLayoutExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    HpObjLayout selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpObjLayout record, @Param("example") HpObjLayoutExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpObjLayout record, @Param("example") HpObjLayoutExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpObjLayout record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpObjLayout record);
}
