package com.neusoft.designer.service.mapper;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpOdAttribute;
import com.neusoft.designer.service.domain.HpOdAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpOdAttributeMapper extends GenDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    long countByExample(HpOdAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    int deleteByExample(HpOdAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    int insert(HpOdAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    int insertSelective(HpOdAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    List<HpOdAttribute> selectByExample(HpOdAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    HpOdAttribute selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpOdAttribute record, @Param("example") HpOdAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpOdAttribute record, @Param("example") HpOdAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpOdAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpOdAttribute record);
}