package com.neusoft.designer.service.mapper;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpOdTemplateInstance;
import com.neusoft.designer.service.domain.HpOdTemplateInstanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpOdTemplateInstanceMapper extends GenDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE_INSTANCE
     *
     * @mbg.generated
     */
    long countByExample(HpOdTemplateInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE_INSTANCE
     *
     * @mbg.generated
     */
    int deleteByExample(HpOdTemplateInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE_INSTANCE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE_INSTANCE
     *
     * @mbg.generated
     */
    int insert(HpOdTemplateInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE_INSTANCE
     *
     * @mbg.generated
     */
    int insertSelective(HpOdTemplateInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE_INSTANCE
     *
     * @mbg.generated
     */
    List<HpOdTemplateInstance> selectByExample(HpOdTemplateInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE_INSTANCE
     *
     * @mbg.generated
     */
    HpOdTemplateInstance selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE_INSTANCE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpOdTemplateInstance record, @Param("example") HpOdTemplateInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE_INSTANCE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpOdTemplateInstance record, @Param("example") HpOdTemplateInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE_INSTANCE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpOdTemplateInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE_INSTANCE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpOdTemplateInstance record);
}