package com.neusoft.designer.service.mapper;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpOdEnumValue;
import com.neusoft.designer.service.domain.HpOdEnumValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpOdEnumValueMapper extends GenDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM_VALUE
     *
     * @mbg.generated
     */
    long countByExample(HpOdEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM_VALUE
     *
     * @mbg.generated
     */
    int deleteByExample(HpOdEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM_VALUE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM_VALUE
     *
     * @mbg.generated
     */
    int insert(HpOdEnumValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM_VALUE
     *
     * @mbg.generated
     */
    int insertSelective(HpOdEnumValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM_VALUE
     *
     * @mbg.generated
     */
    List<HpOdEnumValue> selectByExample(HpOdEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM_VALUE
     *
     * @mbg.generated
     */
    HpOdEnumValue selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM_VALUE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpOdEnumValue record, @Param("example") HpOdEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM_VALUE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpOdEnumValue record, @Param("example") HpOdEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM_VALUE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpOdEnumValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM_VALUE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpOdEnumValue record);
}