package com.neusoft.designer.service.mapper;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpOdTemplate;
import com.neusoft.designer.service.domain.HpOdTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpOdTemplateMapper extends GenDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    long countByExample(HpOdTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    int deleteByExample(HpOdTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    int insert(HpOdTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    int insertSelective(HpOdTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    List<HpOdTemplate> selectByExample(HpOdTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    HpOdTemplate selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpOdTemplate record, @Param("example") HpOdTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpOdTemplate record, @Param("example") HpOdTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpOdTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpOdTemplate record);
}