package com.neusoft.designer.service.mapper;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpOdQueryTemplate;
import com.neusoft.designer.service.domain.HpOdQueryTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpOdQueryTemplateMapper extends GenDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_QUERY_TEMPLATE
     *
     * @mbg.generated
     */
    long countByExample(HpOdQueryTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_QUERY_TEMPLATE
     *
     * @mbg.generated
     */
    int deleteByExample(HpOdQueryTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_QUERY_TEMPLATE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_QUERY_TEMPLATE
     *
     * @mbg.generated
     */
    int insert(HpOdQueryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_QUERY_TEMPLATE
     *
     * @mbg.generated
     */
    int insertSelective(HpOdQueryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_QUERY_TEMPLATE
     *
     * @mbg.generated
     */
    List<HpOdQueryTemplate> selectByExample(HpOdQueryTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_QUERY_TEMPLATE
     *
     * @mbg.generated
     */
    HpOdQueryTemplate selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_QUERY_TEMPLATE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpOdQueryTemplate record, @Param("example") HpOdQueryTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_QUERY_TEMPLATE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpOdQueryTemplate record, @Param("example") HpOdQueryTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_QUERY_TEMPLATE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpOdQueryTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_QUERY_TEMPLATE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpOdQueryTemplate record);
}