package com.neusoft.designer.service.mapper;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpOdClass;
import com.neusoft.designer.service.domain.HpOdClassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpOdClassMapper extends GenDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_CLASS
     *
     * @mbg.generated
     */
    long countByExample(HpOdClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_CLASS
     *
     * @mbg.generated
     */
    int deleteByExample(HpOdClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_CLASS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_CLASS
     *
     * @mbg.generated
     */
    int insert(HpOdClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_CLASS
     *
     * @mbg.generated
     */
    int insertSelective(HpOdClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_CLASS
     *
     * @mbg.generated
     */
    List<HpOdClass> selectByExample(HpOdClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_CLASS
     *
     * @mbg.generated
     */
    HpOdClass selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_CLASS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpOdClass record, @Param("example") HpOdClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_CLASS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpOdClass record, @Param("example") HpOdClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_CLASS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpOdClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_CLASS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpOdClass record);
}