package com.neusoft.designer.service.mapper;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpOdEnum;
import com.neusoft.designer.service.domain.HpOdEnumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpOdEnumMapper extends GenDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM
     *
     * @mbg.generated
     */
    long countByExample(HpOdEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM
     *
     * @mbg.generated
     */
    int deleteByExample(HpOdEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM
     *
     * @mbg.generated
     */
    int insert(HpOdEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM
     *
     * @mbg.generated
     */
    int insertSelective(HpOdEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM
     *
     * @mbg.generated
     */
    List<HpOdEnum> selectByExample(HpOdEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM
     *
     * @mbg.generated
     */
    HpOdEnum selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpOdEnum record, @Param("example") HpOdEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpOdEnum record, @Param("example") HpOdEnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpOdEnum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_ENUM
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpOdEnum record);
}