package com.neusoft.designer.service.mapper;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.HpOdStyleTemplate;
import com.neusoft.designer.service.domain.HpOdStyleTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HpOdStyleTemplateMapper extends GenDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_STYLE_TEMPLATE
     *
     * @mbg.generated
     */
    long countByExample(HpOdStyleTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_STYLE_TEMPLATE
     *
     * @mbg.generated
     */
    int deleteByExample(HpOdStyleTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_STYLE_TEMPLATE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_STYLE_TEMPLATE
     *
     * @mbg.generated
     */
    int insert(HpOdStyleTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_STYLE_TEMPLATE
     *
     * @mbg.generated
     */
    int insertSelective(HpOdStyleTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_STYLE_TEMPLATE
     *
     * @mbg.generated
     */
    List<HpOdStyleTemplate> selectByExample(HpOdStyleTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_STYLE_TEMPLATE
     *
     * @mbg.generated
     */
    HpOdStyleTemplate selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_STYLE_TEMPLATE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpOdStyleTemplate record, @Param("example") HpOdStyleTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_STYLE_TEMPLATE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpOdStyleTemplate record, @Param("example") HpOdStyleTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_STYLE_TEMPLATE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpOdStyleTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_STYLE_TEMPLATE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpOdStyleTemplate record);
}