package com.neusoft.designer.service.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.PObjEnum;
import com.neusoft.designer.service.domain.PObjEnumExample;

public interface PObjEnumMapper extends GenDao {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM
     *
     * @mbg.generated
     */
    long countByExample(PObjEnumExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM
     *
     * @mbg.generated
     */
    int deleteByExample(PObjEnumExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM
     *
     * @mbg.generated
     */
    int insert(PObjEnum record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM
     *
     * @mbg.generated
     */
    int insertSelective(PObjEnum record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM
     *
     * @mbg.generated
     */
    List<PObjEnum> selectByExample(PObjEnumExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM
     *
     * @mbg.generated
     */
    PObjEnum selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PObjEnum record, @Param("example") PObjEnumExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PObjEnum record, @Param("example") PObjEnumExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PObjEnum record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PObjEnum record);
}
