package com.neusoft.designer.service.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.PObjAttribute;
import com.neusoft.designer.service.domain.PObjAttributeExample;

public interface PObjAttributeMapper extends GenDao {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    long countByExample(PObjAttributeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int deleteByExample(PObjAttributeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int insert(PObjAttribute record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int insertSelective(PObjAttribute record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    List<PObjAttribute> selectByExample(PObjAttributeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    PObjAttribute selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PObjAttribute record, @Param("example") PObjAttributeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PObjAttribute record, @Param("example") PObjAttributeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PObjAttribute record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ATTRIBUTE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PObjAttribute record);
}
