package com.neusoft.designer.service.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.PObjLayout;
import com.neusoft.designer.service.domain.PObjLayoutExample;

public interface PObjLayoutMapper extends GenDao {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    long countByExample(PObjLayoutExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int deleteByExample(PObjLayoutExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int insert(PObjLayout record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int insertSelective(PObjLayout record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    List<PObjLayout> selectByExample(PObjLayoutExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    PObjLayout selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PObjLayout record, @Param("example") PObjLayoutExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PObjLayout record, @Param("example") PObjLayoutExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PObjLayout record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PObjLayout record);
}
