package com.neusoft.designer.service.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.PObjORG;
import com.neusoft.designer.service.domain.PObjORGExample;

public interface PObjORGMapper extends GenDao {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ORG
     *
     * @mbg.generated
     */
    long countByExample(PObjORGExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ORG
     *
     * @mbg.generated
     */
    int deleteByExample(PObjORGExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ORG
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ORG
     *
     * @mbg.generated
     */
    int insert(PObjORG record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ORG
     *
     * @mbg.generated
     */
    int insertSelective(PObjORG record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ORG
     *
     * @mbg.generated
     */
    List<PObjORG> selectByExample(PObjORGExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ORG
     *
     * @mbg.generated
     */
    PObjORG selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ORG
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PObjORG record, @Param("example") PObjORGExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ORG
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PObjORG record, @Param("example") PObjORGExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ORG
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PObjORG record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ORG
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PObjORG record);
}
