package com.neusoft.designer.service.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.neusoft.core.dao.GenDao;
import com.neusoft.designer.service.domain.PObjEnumValue;
import com.neusoft.designer.service.domain.PObjEnumValueExample;

public interface PObjEnumValueMapper extends GenDao {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    long countByExample(PObjEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int deleteByExample(PObjEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int insert(PObjEnumValue record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int insertSelective(PObjEnumValue record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    List<PObjEnumValue> selectByExample(PObjEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    PObjEnumValue selectByPrimaryKey(String gid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PObjEnumValue record, @Param("example") PObjEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PObjEnumValue record, @Param("example") PObjEnumValueExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PObjEnumValue record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PObjEnumValue record);
}
