package com.neusoft.designer.service.domain;

import com.neusoft.core.dao.GenDO;
import java.io.Serializable;

public class HpOdTemplate extends GenDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HP_OD_TEMPLATE.HP_OD_OBJECT_GID
     *
     * @mbg.generated
     */
    private String hpOdObjectGid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HP_OD_TEMPLATE.CODE
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HP_OD_TEMPLATE.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HP_OD_TEMPLATE.DISPLAY_NAME
     *
     * @mbg.generated
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HP_OD_TEMPLATE.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HP_OD_TEMPLATE.HP_OD_OBJECT_GID
     *
     * @return the value of HP_OD_TEMPLATE.HP_OD_OBJECT_GID
     *
     * @mbg.generated
     */
    public String getHpOdObjectGid() {
        return hpOdObjectGid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HP_OD_TEMPLATE.HP_OD_OBJECT_GID
     *
     * @param hpOdObjectGid the value for HP_OD_TEMPLATE.HP_OD_OBJECT_GID
     *
     * @mbg.generated
     */
    public void setHpOdObjectGid(String hpOdObjectGid) {
        this.hpOdObjectGid = hpOdObjectGid == null ? null : hpOdObjectGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HP_OD_TEMPLATE.CODE
     *
     * @return the value of HP_OD_TEMPLATE.CODE
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HP_OD_TEMPLATE.CODE
     *
     * @param code the value for HP_OD_TEMPLATE.CODE
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HP_OD_TEMPLATE.NAME
     *
     * @return the value of HP_OD_TEMPLATE.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HP_OD_TEMPLATE.NAME
     *
     * @param name the value for HP_OD_TEMPLATE.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HP_OD_TEMPLATE.DISPLAY_NAME
     *
     * @return the value of HP_OD_TEMPLATE.DISPLAY_NAME
     *
     * @mbg.generated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HP_OD_TEMPLATE.DISPLAY_NAME
     *
     * @param displayName the value for HP_OD_TEMPLATE.DISPLAY_NAME
     *
     * @mbg.generated
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HP_OD_TEMPLATE.DESCRIPTION
     *
     * @return the value of HP_OD_TEMPLATE.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HP_OD_TEMPLATE.DESCRIPTION
     *
     * @param description the value for HP_OD_TEMPLATE.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HpOdTemplate other = (HpOdTemplate) that;
        return (this.getGid() == null ? other.getGid() == null : this.getGid().equals(other.getGid()))
            && (this.getHpOdObjectGid() == null ? other.getHpOdObjectGid() == null : this.getHpOdObjectGid().equals(other.getHpOdObjectGid()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDisplayName() == null ? other.getDisplayName() == null : this.getDisplayName().equals(other.getDisplayName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDelete() == null ? other.getDelete() == null : this.getDelete().equals(other.getDelete()))
            && (this.getActive() == null ? other.getActive() == null : this.getActive().equals(other.getActive()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGid() == null) ? 0 : getGid().hashCode());
        result = prime * result + ((getHpOdObjectGid() == null) ? 0 : getHpOdObjectGid().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDisplayName() == null) ? 0 : getDisplayName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDelete() == null) ? 0 : getDelete().hashCode());
        result = prime * result + ((getActive() == null) ? 0 : getActive().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HP_OD_TEMPLATE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hpOdObjectGid=").append(hpOdObjectGid);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", displayName=").append(displayName);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}