package com.neusoft.designer.service.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.neusoft.core.dao.GenExample;

public class HpOdAttributeExample extends GenExample {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    protected String         orderByClause;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    protected boolean        distinct;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    public HpOdAttributeExample(){
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> isFixedlengthCriteria;

        protected List<Criterion> isRequiredCriteria;

        protected List<Criterion> isReadonlyCriteria;

        protected List<Criterion> isUniqueCriteria;

        protected List<Criterion> isDatafilterCriteria;

        protected List<Criterion> deleteCriteria;

        protected List<Criterion> activeCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria(){
            super();
            criteria = new ArrayList<Criterion>();
            isFixedlengthCriteria = new ArrayList<Criterion>();
            isRequiredCriteria = new ArrayList<Criterion>();
            isReadonlyCriteria = new ArrayList<Criterion>();
            isUniqueCriteria = new ArrayList<Criterion>();
            isDatafilterCriteria = new ArrayList<Criterion>();
            deleteCriteria = new ArrayList<Criterion>();
            activeCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getIsFixedlengthCriteria() {
            return isFixedlengthCriteria;
        }

        protected void addIsFixedlengthCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            isFixedlengthCriteria.add(new Criterion(condition, value,
                                                    "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        protected void addIsFixedlengthCriterion(String condition, Boolean value1, Boolean value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            isFixedlengthCriteria.add(new Criterion(condition, value1, value2,
                                                    "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getIsRequiredCriteria() {
            return isRequiredCriteria;
        }

        protected void addIsRequiredCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            isRequiredCriteria.add(new Criterion(condition, value, "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        protected void addIsRequiredCriterion(String condition, Boolean value1, Boolean value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            isRequiredCriteria.add(new Criterion(condition, value1, value2,
                                                 "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getIsReadonlyCriteria() {
            return isReadonlyCriteria;
        }

        protected void addIsReadonlyCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            isReadonlyCriteria.add(new Criterion(condition, value, "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        protected void addIsReadonlyCriterion(String condition, Boolean value1, Boolean value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            isReadonlyCriteria.add(new Criterion(condition, value1, value2,
                                                 "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getIsUniqueCriteria() {
            return isUniqueCriteria;
        }

        protected void addIsUniqueCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            isUniqueCriteria.add(new Criterion(condition, value, "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        protected void addIsUniqueCriterion(String condition, Boolean value1, Boolean value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            isUniqueCriteria.add(new Criterion(condition, value1, value2,
                                               "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getIsDatafilterCriteria() {
            return isDatafilterCriteria;
        }

        protected void addIsDatafilterCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            isDatafilterCriteria.add(new Criterion(condition, value,
                                                   "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        protected void addIsDatafilterCriterion(String condition, Boolean value1, Boolean value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            isDatafilterCriteria.add(new Criterion(condition, value1, value2,
                                                   "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getDeleteCriteria() {
            return deleteCriteria;
        }

        protected void addDeleteCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            deleteCriteria.add(new Criterion(condition, value, "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        protected void addDeleteCriterion(String condition, Boolean value1, Boolean value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            deleteCriteria.add(new Criterion(condition, value1, value2,
                                             "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getActiveCriteria() {
            return activeCriteria;
        }

        protected void addActiveCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            activeCriteria.add(new Criterion(condition, value, "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        protected void addActiveCriterion(String condition, Boolean value1, Boolean value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            activeCriteria.add(new Criterion(condition, value1, value2,
                                             "com.neusoft.core.dao.wrapper.BooleanTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0 || isFixedlengthCriteria.size() > 0 || isRequiredCriteria.size() > 0
                   || isReadonlyCriteria.size() > 0 || isUniqueCriteria.size() > 0 || isDatafilterCriteria.size() > 0
                   || deleteCriteria.size() > 0 || activeCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(isFixedlengthCriteria);
                allCriteria.addAll(isRequiredCriteria);
                allCriteria.addAll(isReadonlyCriteria);
                allCriteria.addAll(isUniqueCriteria);
                allCriteria.addAll(isDatafilterCriteria);
                allCriteria.addAll(deleteCriteria);
                allCriteria.addAll(activeCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andGidIsNull() {
            addCriterion("GID is null");
            return (Criteria) this;
        }

        public Criteria andGidIsNotNull() {
            addCriterion("GID is not null");
            return (Criteria) this;
        }

        public Criteria andGidEqualTo(String value) {
            addCriterion("GID =", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotEqualTo(String value) {
            addCriterion("GID <>", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThan(String value) {
            addCriterion("GID >", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThanOrEqualTo(String value) {
            addCriterion("GID >=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThan(String value) {
            addCriterion("GID <", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThanOrEqualTo(String value) {
            addCriterion("GID <=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLike(String value) {
            addCriterion("GID like", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotLike(String value) {
            addCriterion("GID not like", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidIn(List<String> values) {
            addCriterion("GID in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotIn(List<String> values) {
            addCriterion("GID not in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidBetween(String value1, String value2) {
            addCriterion("GID between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotBetween(String value1, String value2) {
            addCriterion("GID not between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidIsNull() {
            addCriterion("HP_OD_CLASS_GID is null");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidIsNotNull() {
            addCriterion("HP_OD_CLASS_GID is not null");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidEqualTo(String value) {
            addCriterion("HP_OD_CLASS_GID =", value, "hpOdClassGid");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidNotEqualTo(String value) {
            addCriterion("HP_OD_CLASS_GID <>", value, "hpOdClassGid");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidGreaterThan(String value) {
            addCriterion("HP_OD_CLASS_GID >", value, "hpOdClassGid");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidGreaterThanOrEqualTo(String value) {
            addCriterion("HP_OD_CLASS_GID >=", value, "hpOdClassGid");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidLessThan(String value) {
            addCriterion("HP_OD_CLASS_GID <", value, "hpOdClassGid");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidLessThanOrEqualTo(String value) {
            addCriterion("HP_OD_CLASS_GID <=", value, "hpOdClassGid");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidLike(String value) {
            addCriterion("HP_OD_CLASS_GID like", value, "hpOdClassGid");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidNotLike(String value) {
            addCriterion("HP_OD_CLASS_GID not like", value, "hpOdClassGid");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidIn(List<String> values) {
            addCriterion("HP_OD_CLASS_GID in", values, "hpOdClassGid");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidNotIn(List<String> values) {
            addCriterion("HP_OD_CLASS_GID not in", values, "hpOdClassGid");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidBetween(String value1, String value2) {
            addCriterion("HP_OD_CLASS_GID between", value1, value2, "hpOdClassGid");
            return (Criteria) this;
        }

        public Criteria andHpOdClassGidNotBetween(String value1, String value2) {
            addCriterion("HP_OD_CLASS_GID not between", value1, value2, "hpOdClassGid");
            return (Criteria) this;
        }

        public Criteria andSeqIsNull() {
            addCriterion("SEQ is null");
            return (Criteria) this;
        }

        public Criteria andSeqIsNotNull() {
            addCriterion("SEQ is not null");
            return (Criteria) this;
        }

        public Criteria andSeqEqualTo(Short value) {
            addCriterion("SEQ =", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotEqualTo(Short value) {
            addCriterion("SEQ <>", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThan(Short value) {
            addCriterion("SEQ >", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThanOrEqualTo(Short value) {
            addCriterion("SEQ >=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThan(Short value) {
            addCriterion("SEQ <", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqLessThanOrEqualTo(Short value) {
            addCriterion("SEQ <=", value, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqIn(List<Short> values) {
            addCriterion("SEQ in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotIn(List<Short> values) {
            addCriterion("SEQ not in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqBetween(Short value1, Short value2) {
            addCriterion("SEQ between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotBetween(Short value1, Short value2) {
            addCriterion("SEQ not between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andFieldNameIsNull() {
            addCriterion("FIELD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFieldNameIsNotNull() {
            addCriterion("FIELD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFieldNameEqualTo(String value) {
            addCriterion("FIELD_NAME =", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameNotEqualTo(String value) {
            addCriterion("FIELD_NAME <>", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameGreaterThan(String value) {
            addCriterion("FIELD_NAME >", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameGreaterThanOrEqualTo(String value) {
            addCriterion("FIELD_NAME >=", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameLessThan(String value) {
            addCriterion("FIELD_NAME <", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameLessThanOrEqualTo(String value) {
            addCriterion("FIELD_NAME <=", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameLike(String value) {
            addCriterion("FIELD_NAME like", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameNotLike(String value) {
            addCriterion("FIELD_NAME not like", value, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameIn(List<String> values) {
            addCriterion("FIELD_NAME in", values, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameNotIn(List<String> values) {
            addCriterion("FIELD_NAME not in", values, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameBetween(String value1, String value2) {
            addCriterion("FIELD_NAME between", value1, value2, "fieldName");
            return (Criteria) this;
        }

        public Criteria andFieldNameNotBetween(String value1, String value2) {
            addCriterion("FIELD_NAME not between", value1, value2, "fieldName");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDisplayNameIsNull() {
            addCriterion("DISPLAY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDisplayNameIsNotNull() {
            addCriterion("DISPLAY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayNameEqualTo(String value) {
            addCriterion("DISPLAY_NAME =", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotEqualTo(String value) {
            addCriterion("DISPLAY_NAME <>", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameGreaterThan(String value) {
            addCriterion("DISPLAY_NAME >", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameGreaterThanOrEqualTo(String value) {
            addCriterion("DISPLAY_NAME >=", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameLessThan(String value) {
            addCriterion("DISPLAY_NAME <", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameLessThanOrEqualTo(String value) {
            addCriterion("DISPLAY_NAME <=", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameLike(String value) {
            addCriterion("DISPLAY_NAME like", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotLike(String value) {
            addCriterion("DISPLAY_NAME not like", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameIn(List<String> values) {
            addCriterion("DISPLAY_NAME in", values, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotIn(List<String> values) {
            addCriterion("DISPLAY_NAME not in", values, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameBetween(String value1, String value2) {
            addCriterion("DISPLAY_NAME between", value1, value2, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotBetween(String value1, String value2) {
            addCriterion("DISPLAY_NAME not between", value1, value2, "displayName");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNull() {
            addCriterion("DATA_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNotNull() {
            addCriterion("DATA_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDataTypeEqualTo(Short value) {
            addCriterion("DATA_TYPE =", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotEqualTo(Short value) {
            addCriterion("DATA_TYPE <>", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThan(Short value) {
            addCriterion("DATA_TYPE >", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("DATA_TYPE >=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThan(Short value) {
            addCriterion("DATA_TYPE <", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThanOrEqualTo(Short value) {
            addCriterion("DATA_TYPE <=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeIn(List<Short> values) {
            addCriterion("DATA_TYPE in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotIn(List<Short> values) {
            addCriterion("DATA_TYPE not in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeBetween(Short value1, Short value2) {
            addCriterion("DATA_TYPE between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotBetween(Short value1, Short value2) {
            addCriterion("DATA_TYPE not between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andTypeValueIsNull() {
            addCriterion("TYPE_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andTypeValueIsNotNull() {
            addCriterion("TYPE_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeValueEqualTo(String value) {
            addCriterion("TYPE_VALUE =", value, "typeValue");
            return (Criteria) this;
        }

        public Criteria andTypeValueNotEqualTo(String value) {
            addCriterion("TYPE_VALUE <>", value, "typeValue");
            return (Criteria) this;
        }

        public Criteria andTypeValueGreaterThan(String value) {
            addCriterion("TYPE_VALUE >", value, "typeValue");
            return (Criteria) this;
        }

        public Criteria andTypeValueGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE_VALUE >=", value, "typeValue");
            return (Criteria) this;
        }

        public Criteria andTypeValueLessThan(String value) {
            addCriterion("TYPE_VALUE <", value, "typeValue");
            return (Criteria) this;
        }

        public Criteria andTypeValueLessThanOrEqualTo(String value) {
            addCriterion("TYPE_VALUE <=", value, "typeValue");
            return (Criteria) this;
        }

        public Criteria andTypeValueLike(String value) {
            addCriterion("TYPE_VALUE like", value, "typeValue");
            return (Criteria) this;
        }

        public Criteria andTypeValueNotLike(String value) {
            addCriterion("TYPE_VALUE not like", value, "typeValue");
            return (Criteria) this;
        }

        public Criteria andTypeValueIn(List<String> values) {
            addCriterion("TYPE_VALUE in", values, "typeValue");
            return (Criteria) this;
        }

        public Criteria andTypeValueNotIn(List<String> values) {
            addCriterion("TYPE_VALUE not in", values, "typeValue");
            return (Criteria) this;
        }

        public Criteria andTypeValueBetween(String value1, String value2) {
            addCriterion("TYPE_VALUE between", value1, value2, "typeValue");
            return (Criteria) this;
        }

        public Criteria andTypeValueNotBetween(String value1, String value2) {
            addCriterion("TYPE_VALUE not between", value1, value2, "typeValue");
            return (Criteria) this;
        }

        public Criteria andIsFixedlengthIsNull() {
            addCriterion("IS_FIXEDLENGTH is null");
            return (Criteria) this;
        }

        public Criteria andIsFixedlengthIsNotNull() {
            addCriterion("IS_FIXEDLENGTH is not null");
            return (Criteria) this;
        }

        public Criteria andIsFixedlengthEqualTo(Boolean value) {
            addIsFixedlengthCriterion("IS_FIXEDLENGTH =", value, "isFixedlength");
            return (Criteria) this;
        }

        public Criteria andIsFixedlengthNotEqualTo(Boolean value) {
            addIsFixedlengthCriterion("IS_FIXEDLENGTH <>", value, "isFixedlength");
            return (Criteria) this;
        }

        public Criteria andIsFixedlengthGreaterThan(Boolean value) {
            addIsFixedlengthCriterion("IS_FIXEDLENGTH >", value, "isFixedlength");
            return (Criteria) this;
        }

        public Criteria andIsFixedlengthGreaterThanOrEqualTo(Boolean value) {
            addIsFixedlengthCriterion("IS_FIXEDLENGTH >=", value, "isFixedlength");
            return (Criteria) this;
        }

        public Criteria andIsFixedlengthLessThan(Boolean value) {
            addIsFixedlengthCriterion("IS_FIXEDLENGTH <", value, "isFixedlength");
            return (Criteria) this;
        }

        public Criteria andIsFixedlengthLessThanOrEqualTo(Boolean value) {
            addIsFixedlengthCriterion("IS_FIXEDLENGTH <=", value, "isFixedlength");
            return (Criteria) this;
        }

        public Criteria andIsFixedlengthIn(List<Boolean> values) {
            addIsFixedlengthCriterion("IS_FIXEDLENGTH in", values, "isFixedlength");
            return (Criteria) this;
        }

        public Criteria andIsFixedlengthNotIn(List<Boolean> values) {
            addIsFixedlengthCriterion("IS_FIXEDLENGTH not in", values, "isFixedlength");
            return (Criteria) this;
        }

        public Criteria andIsFixedlengthBetween(Boolean value1, Boolean value2) {
            addIsFixedlengthCriterion("IS_FIXEDLENGTH between", value1, value2, "isFixedlength");
            return (Criteria) this;
        }

        public Criteria andIsFixedlengthNotBetween(Boolean value1, Boolean value2) {
            addIsFixedlengthCriterion("IS_FIXEDLENGTH not between", value1, value2, "isFixedlength");
            return (Criteria) this;
        }

        public Criteria andAttrLengthIsNull() {
            addCriterion("ATTR_LENGTH is null");
            return (Criteria) this;
        }

        public Criteria andAttrLengthIsNotNull() {
            addCriterion("ATTR_LENGTH is not null");
            return (Criteria) this;
        }

        public Criteria andAttrLengthEqualTo(Short value) {
            addCriterion("ATTR_LENGTH =", value, "attrLength");
            return (Criteria) this;
        }

        public Criteria andAttrLengthNotEqualTo(Short value) {
            addCriterion("ATTR_LENGTH <>", value, "attrLength");
            return (Criteria) this;
        }

        public Criteria andAttrLengthGreaterThan(Short value) {
            addCriterion("ATTR_LENGTH >", value, "attrLength");
            return (Criteria) this;
        }

        public Criteria andAttrLengthGreaterThanOrEqualTo(Short value) {
            addCriterion("ATTR_LENGTH >=", value, "attrLength");
            return (Criteria) this;
        }

        public Criteria andAttrLengthLessThan(Short value) {
            addCriterion("ATTR_LENGTH <", value, "attrLength");
            return (Criteria) this;
        }

        public Criteria andAttrLengthLessThanOrEqualTo(Short value) {
            addCriterion("ATTR_LENGTH <=", value, "attrLength");
            return (Criteria) this;
        }

        public Criteria andAttrLengthIn(List<Short> values) {
            addCriterion("ATTR_LENGTH in", values, "attrLength");
            return (Criteria) this;
        }

        public Criteria andAttrLengthNotIn(List<Short> values) {
            addCriterion("ATTR_LENGTH not in", values, "attrLength");
            return (Criteria) this;
        }

        public Criteria andAttrLengthBetween(Short value1, Short value2) {
            addCriterion("ATTR_LENGTH between", value1, value2, "attrLength");
            return (Criteria) this;
        }

        public Criteria andAttrLengthNotBetween(Short value1, Short value2) {
            addCriterion("ATTR_LENGTH not between", value1, value2, "attrLength");
            return (Criteria) this;
        }

        public Criteria andAttrPrecisionIsNull() {
            addCriterion("ATTR_PRECISION is null");
            return (Criteria) this;
        }

        public Criteria andAttrPrecisionIsNotNull() {
            addCriterion("ATTR_PRECISION is not null");
            return (Criteria) this;
        }

        public Criteria andAttrPrecisionEqualTo(Short value) {
            addCriterion("ATTR_PRECISION =", value, "attrPrecision");
            return (Criteria) this;
        }

        public Criteria andAttrPrecisionNotEqualTo(Short value) {
            addCriterion("ATTR_PRECISION <>", value, "attrPrecision");
            return (Criteria) this;
        }

        public Criteria andAttrPrecisionGreaterThan(Short value) {
            addCriterion("ATTR_PRECISION >", value, "attrPrecision");
            return (Criteria) this;
        }

        public Criteria andAttrPrecisionGreaterThanOrEqualTo(Short value) {
            addCriterion("ATTR_PRECISION >=", value, "attrPrecision");
            return (Criteria) this;
        }

        public Criteria andAttrPrecisionLessThan(Short value) {
            addCriterion("ATTR_PRECISION <", value, "attrPrecision");
            return (Criteria) this;
        }

        public Criteria andAttrPrecisionLessThanOrEqualTo(Short value) {
            addCriterion("ATTR_PRECISION <=", value, "attrPrecision");
            return (Criteria) this;
        }

        public Criteria andAttrPrecisionIn(List<Short> values) {
            addCriterion("ATTR_PRECISION in", values, "attrPrecision");
            return (Criteria) this;
        }

        public Criteria andAttrPrecisionNotIn(List<Short> values) {
            addCriterion("ATTR_PRECISION not in", values, "attrPrecision");
            return (Criteria) this;
        }

        public Criteria andAttrPrecisionBetween(Short value1, Short value2) {
            addCriterion("ATTR_PRECISION between", value1, value2, "attrPrecision");
            return (Criteria) this;
        }

        public Criteria andAttrPrecisionNotBetween(Short value1, Short value2) {
            addCriterion("ATTR_PRECISION not between", value1, value2, "attrPrecision");
            return (Criteria) this;
        }

        public Criteria andMaxValueIsNull() {
            addCriterion("MAX_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andMaxValueIsNotNull() {
            addCriterion("MAX_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andMaxValueEqualTo(String value) {
            addCriterion("MAX_VALUE =", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueNotEqualTo(String value) {
            addCriterion("MAX_VALUE <>", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueGreaterThan(String value) {
            addCriterion("MAX_VALUE >", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueGreaterThanOrEqualTo(String value) {
            addCriterion("MAX_VALUE >=", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueLessThan(String value) {
            addCriterion("MAX_VALUE <", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueLessThanOrEqualTo(String value) {
            addCriterion("MAX_VALUE <=", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueLike(String value) {
            addCriterion("MAX_VALUE like", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueNotLike(String value) {
            addCriterion("MAX_VALUE not like", value, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueIn(List<String> values) {
            addCriterion("MAX_VALUE in", values, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueNotIn(List<String> values) {
            addCriterion("MAX_VALUE not in", values, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueBetween(String value1, String value2) {
            addCriterion("MAX_VALUE between", value1, value2, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMaxValueNotBetween(String value1, String value2) {
            addCriterion("MAX_VALUE not between", value1, value2, "maxValue");
            return (Criteria) this;
        }

        public Criteria andMinValueIsNull() {
            addCriterion("MIN_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andMinValueIsNotNull() {
            addCriterion("MIN_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andMinValueEqualTo(String value) {
            addCriterion("MIN_VALUE =", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueNotEqualTo(String value) {
            addCriterion("MIN_VALUE <>", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueGreaterThan(String value) {
            addCriterion("MIN_VALUE >", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueGreaterThanOrEqualTo(String value) {
            addCriterion("MIN_VALUE >=", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueLessThan(String value) {
            addCriterion("MIN_VALUE <", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueLessThanOrEqualTo(String value) {
            addCriterion("MIN_VALUE <=", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueLike(String value) {
            addCriterion("MIN_VALUE like", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueNotLike(String value) {
            addCriterion("MIN_VALUE not like", value, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueIn(List<String> values) {
            addCriterion("MIN_VALUE in", values, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueNotIn(List<String> values) {
            addCriterion("MIN_VALUE not in", values, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueBetween(String value1, String value2) {
            addCriterion("MIN_VALUE between", value1, value2, "minValue");
            return (Criteria) this;
        }

        public Criteria andMinValueNotBetween(String value1, String value2) {
            addCriterion("MIN_VALUE not between", value1, value2, "minValue");
            return (Criteria) this;
        }

        public Criteria andDefaultValueIsNull() {
            addCriterion("DEFAULT_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andDefaultValueIsNotNull() {
            addCriterion("DEFAULT_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultValueEqualTo(String value) {
            addCriterion("DEFAULT_VALUE =", value, "defaultValue");
            return (Criteria) this;
        }

        public Criteria andDefaultValueNotEqualTo(String value) {
            addCriterion("DEFAULT_VALUE <>", value, "defaultValue");
            return (Criteria) this;
        }

        public Criteria andDefaultValueGreaterThan(String value) {
            addCriterion("DEFAULT_VALUE >", value, "defaultValue");
            return (Criteria) this;
        }

        public Criteria andDefaultValueGreaterThanOrEqualTo(String value) {
            addCriterion("DEFAULT_VALUE >=", value, "defaultValue");
            return (Criteria) this;
        }

        public Criteria andDefaultValueLessThan(String value) {
            addCriterion("DEFAULT_VALUE <", value, "defaultValue");
            return (Criteria) this;
        }

        public Criteria andDefaultValueLessThanOrEqualTo(String value) {
            addCriterion("DEFAULT_VALUE <=", value, "defaultValue");
            return (Criteria) this;
        }

        public Criteria andDefaultValueLike(String value) {
            addCriterion("DEFAULT_VALUE like", value, "defaultValue");
            return (Criteria) this;
        }

        public Criteria andDefaultValueNotLike(String value) {
            addCriterion("DEFAULT_VALUE not like", value, "defaultValue");
            return (Criteria) this;
        }

        public Criteria andDefaultValueIn(List<String> values) {
            addCriterion("DEFAULT_VALUE in", values, "defaultValue");
            return (Criteria) this;
        }

        public Criteria andDefaultValueNotIn(List<String> values) {
            addCriterion("DEFAULT_VALUE not in", values, "defaultValue");
            return (Criteria) this;
        }

        public Criteria andDefaultValueBetween(String value1, String value2) {
            addCriterion("DEFAULT_VALUE between", value1, value2, "defaultValue");
            return (Criteria) this;
        }

        public Criteria andDefaultValueNotBetween(String value1, String value2) {
            addCriterion("DEFAULT_VALUE not between", value1, value2, "defaultValue");
            return (Criteria) this;
        }

        public Criteria andIsRequiredIsNull() {
            addCriterion("IS_REQUIRED is null");
            return (Criteria) this;
        }

        public Criteria andIsRequiredIsNotNull() {
            addCriterion("IS_REQUIRED is not null");
            return (Criteria) this;
        }

        public Criteria andIsRequiredEqualTo(Boolean value) {
            addIsRequiredCriterion("IS_REQUIRED =", value, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredNotEqualTo(Boolean value) {
            addIsRequiredCriterion("IS_REQUIRED <>", value, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredGreaterThan(Boolean value) {
            addIsRequiredCriterion("IS_REQUIRED >", value, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredGreaterThanOrEqualTo(Boolean value) {
            addIsRequiredCriterion("IS_REQUIRED >=", value, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredLessThan(Boolean value) {
            addIsRequiredCriterion("IS_REQUIRED <", value, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredLessThanOrEqualTo(Boolean value) {
            addIsRequiredCriterion("IS_REQUIRED <=", value, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredIn(List<Boolean> values) {
            addIsRequiredCriterion("IS_REQUIRED in", values, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredNotIn(List<Boolean> values) {
            addIsRequiredCriterion("IS_REQUIRED not in", values, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredBetween(Boolean value1, Boolean value2) {
            addIsRequiredCriterion("IS_REQUIRED between", value1, value2, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsRequiredNotBetween(Boolean value1, Boolean value2) {
            addIsRequiredCriterion("IS_REQUIRED not between", value1, value2, "isRequired");
            return (Criteria) this;
        }

        public Criteria andIsReadonlyIsNull() {
            addCriterion("IS_READONLY is null");
            return (Criteria) this;
        }

        public Criteria andIsReadonlyIsNotNull() {
            addCriterion("IS_READONLY is not null");
            return (Criteria) this;
        }

        public Criteria andIsReadonlyEqualTo(Boolean value) {
            addIsReadonlyCriterion("IS_READONLY =", value, "isReadonly");
            return (Criteria) this;
        }

        public Criteria andIsReadonlyNotEqualTo(Boolean value) {
            addIsReadonlyCriterion("IS_READONLY <>", value, "isReadonly");
            return (Criteria) this;
        }

        public Criteria andIsReadonlyGreaterThan(Boolean value) {
            addIsReadonlyCriterion("IS_READONLY >", value, "isReadonly");
            return (Criteria) this;
        }

        public Criteria andIsReadonlyGreaterThanOrEqualTo(Boolean value) {
            addIsReadonlyCriterion("IS_READONLY >=", value, "isReadonly");
            return (Criteria) this;
        }

        public Criteria andIsReadonlyLessThan(Boolean value) {
            addIsReadonlyCriterion("IS_READONLY <", value, "isReadonly");
            return (Criteria) this;
        }

        public Criteria andIsReadonlyLessThanOrEqualTo(Boolean value) {
            addIsReadonlyCriterion("IS_READONLY <=", value, "isReadonly");
            return (Criteria) this;
        }

        public Criteria andIsReadonlyIn(List<Boolean> values) {
            addIsReadonlyCriterion("IS_READONLY in", values, "isReadonly");
            return (Criteria) this;
        }

        public Criteria andIsReadonlyNotIn(List<Boolean> values) {
            addIsReadonlyCriterion("IS_READONLY not in", values, "isReadonly");
            return (Criteria) this;
        }

        public Criteria andIsReadonlyBetween(Boolean value1, Boolean value2) {
            addIsReadonlyCriterion("IS_READONLY between", value1, value2, "isReadonly");
            return (Criteria) this;
        }

        public Criteria andIsReadonlyNotBetween(Boolean value1, Boolean value2) {
            addIsReadonlyCriterion("IS_READONLY not between", value1, value2, "isReadonly");
            return (Criteria) this;
        }

        public Criteria andIsUniqueIsNull() {
            addCriterion("IS_UNIQUE is null");
            return (Criteria) this;
        }

        public Criteria andIsUniqueIsNotNull() {
            addCriterion("IS_UNIQUE is not null");
            return (Criteria) this;
        }

        public Criteria andIsUniqueEqualTo(Boolean value) {
            addIsUniqueCriterion("IS_UNIQUE =", value, "isUnique");
            return (Criteria) this;
        }

        public Criteria andIsUniqueNotEqualTo(Boolean value) {
            addIsUniqueCriterion("IS_UNIQUE <>", value, "isUnique");
            return (Criteria) this;
        }

        public Criteria andIsUniqueGreaterThan(Boolean value) {
            addIsUniqueCriterion("IS_UNIQUE >", value, "isUnique");
            return (Criteria) this;
        }

        public Criteria andIsUniqueGreaterThanOrEqualTo(Boolean value) {
            addIsUniqueCriterion("IS_UNIQUE >=", value, "isUnique");
            return (Criteria) this;
        }

        public Criteria andIsUniqueLessThan(Boolean value) {
            addIsUniqueCriterion("IS_UNIQUE <", value, "isUnique");
            return (Criteria) this;
        }

        public Criteria andIsUniqueLessThanOrEqualTo(Boolean value) {
            addIsUniqueCriterion("IS_UNIQUE <=", value, "isUnique");
            return (Criteria) this;
        }

        public Criteria andIsUniqueIn(List<Boolean> values) {
            addIsUniqueCriterion("IS_UNIQUE in", values, "isUnique");
            return (Criteria) this;
        }

        public Criteria andIsUniqueNotIn(List<Boolean> values) {
            addIsUniqueCriterion("IS_UNIQUE not in", values, "isUnique");
            return (Criteria) this;
        }

        public Criteria andIsUniqueBetween(Boolean value1, Boolean value2) {
            addIsUniqueCriterion("IS_UNIQUE between", value1, value2, "isUnique");
            return (Criteria) this;
        }

        public Criteria andIsUniqueNotBetween(Boolean value1, Boolean value2) {
            addIsUniqueCriterion("IS_UNIQUE not between", value1, value2, "isUnique");
            return (Criteria) this;
        }

        public Criteria andIsDatafilterIsNull() {
            addCriterion("IS_DATAFILTER is null");
            return (Criteria) this;
        }

        public Criteria andIsDatafilterIsNotNull() {
            addCriterion("IS_DATAFILTER is not null");
            return (Criteria) this;
        }

        public Criteria andIsDatafilterEqualTo(Boolean value) {
            addIsDatafilterCriterion("IS_DATAFILTER =", value, "isDatafilter");
            return (Criteria) this;
        }

        public Criteria andIsDatafilterNotEqualTo(Boolean value) {
            addIsDatafilterCriterion("IS_DATAFILTER <>", value, "isDatafilter");
            return (Criteria) this;
        }

        public Criteria andIsDatafilterGreaterThan(Boolean value) {
            addIsDatafilterCriterion("IS_DATAFILTER >", value, "isDatafilter");
            return (Criteria) this;
        }

        public Criteria andIsDatafilterGreaterThanOrEqualTo(Boolean value) {
            addIsDatafilterCriterion("IS_DATAFILTER >=", value, "isDatafilter");
            return (Criteria) this;
        }

        public Criteria andIsDatafilterLessThan(Boolean value) {
            addIsDatafilterCriterion("IS_DATAFILTER <", value, "isDatafilter");
            return (Criteria) this;
        }

        public Criteria andIsDatafilterLessThanOrEqualTo(Boolean value) {
            addIsDatafilterCriterion("IS_DATAFILTER <=", value, "isDatafilter");
            return (Criteria) this;
        }

        public Criteria andIsDatafilterIn(List<Boolean> values) {
            addIsDatafilterCriterion("IS_DATAFILTER in", values, "isDatafilter");
            return (Criteria) this;
        }

        public Criteria andIsDatafilterNotIn(List<Boolean> values) {
            addIsDatafilterCriterion("IS_DATAFILTER not in", values, "isDatafilter");
            return (Criteria) this;
        }

        public Criteria andIsDatafilterBetween(Boolean value1, Boolean value2) {
            addIsDatafilterCriterion("IS_DATAFILTER between", value1, value2, "isDatafilter");
            return (Criteria) this;
        }

        public Criteria andIsDatafilterNotBetween(Boolean value1, Boolean value2) {
            addIsDatafilterCriterion("IS_DATAFILTER not between", value1, value2, "isDatafilter");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("CREATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("CREATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("CREATE_BY =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("CREATE_BY <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("CREATE_BY >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_BY >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("CREATE_BY <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("CREATE_BY <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("CREATE_BY like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("CREATE_BY not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("CREATE_BY in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("CREATE_BY not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("CREATE_BY between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("CREATE_BY not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("UPDATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("UPDATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("UPDATE_BY =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("UPDATE_BY <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("UPDATE_BY >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("UPDATE_BY <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("UPDATE_BY like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("UPDATE_BY not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("UPDATE_BY in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("UPDATE_BY not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("UPDATE_BY between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("UPDATE_BY not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteIsNull() {
            addCriterion("IS_DELETE is null");
            return (Criteria) this;
        }

        public Criteria andDeleteIsNotNull() {
            addCriterion("IS_DELETE is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteEqualTo(Boolean value) {
            addDeleteCriterion("IS_DELETE =", value, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteNotEqualTo(Boolean value) {
            addDeleteCriterion("IS_DELETE <>", value, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteGreaterThan(Boolean value) {
            addDeleteCriterion("IS_DELETE >", value, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteGreaterThanOrEqualTo(Boolean value) {
            addDeleteCriterion("IS_DELETE >=", value, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteLessThan(Boolean value) {
            addDeleteCriterion("IS_DELETE <", value, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteLessThanOrEqualTo(Boolean value) {
            addDeleteCriterion("IS_DELETE <=", value, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteIn(List<Boolean> values) {
            addDeleteCriterion("IS_DELETE in", values, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteNotIn(List<Boolean> values) {
            addDeleteCriterion("IS_DELETE not in", values, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteBetween(Boolean value1, Boolean value2) {
            addDeleteCriterion("IS_DELETE between", value1, value2, "delete");
            return (Criteria) this;
        }

        public Criteria andDeleteNotBetween(Boolean value1, Boolean value2) {
            addDeleteCriterion("IS_DELETE not between", value1, value2, "delete");
            return (Criteria) this;
        }

        public Criteria andActiveIsNull() {
            addCriterion("IS_ACTIVE is null");
            return (Criteria) this;
        }

        public Criteria andActiveIsNotNull() {
            addCriterion("IS_ACTIVE is not null");
            return (Criteria) this;
        }

        public Criteria andActiveEqualTo(Boolean value) {
            addActiveCriterion("IS_ACTIVE =", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotEqualTo(Boolean value) {
            addActiveCriterion("IS_ACTIVE <>", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveGreaterThan(Boolean value) {
            addActiveCriterion("IS_ACTIVE >", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveGreaterThanOrEqualTo(Boolean value) {
            addActiveCriterion("IS_ACTIVE >=", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveLessThan(Boolean value) {
            addActiveCriterion("IS_ACTIVE <", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveLessThanOrEqualTo(Boolean value) {
            addActiveCriterion("IS_ACTIVE <=", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveIn(List<Boolean> values) {
            addActiveCriterion("IS_ACTIVE in", values, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotIn(List<Boolean> values) {
            addActiveCriterion("IS_ACTIVE not in", values, "active");
            return (Criteria) this;
        }

        public Criteria andActiveBetween(Boolean value1, Boolean value2) {
            addActiveCriterion("IS_ACTIVE between", value1, value2, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotBetween(Boolean value1, Boolean value2) {
            addActiveCriterion("IS_ACTIVE not between", value1, value2, "active");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria(){
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table HP_OD_ATTRIBUTE
     *
     * @mbg.generated
     */
    public static class Criterion {

        private String  condition;

        private Object  value;

        private Object  secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String  typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition){
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler){
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value){
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler){
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue){
            this(condition, value, secondValue, null);
        }
    }
}
