package com.neusoft.designer.service.domain;

import java.io.Serializable;

import com.neusoft.core.dao.GenDO;

public class PObjEnumValue extends GenDO implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * P_OBJ_ENUM_VALUE.P_OBJ_ENUM_GID
     *
     * @mbg.generated
     */
    private String            pObjEnumGid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * P_OBJ_ENUM_VALUE.CODE
     *
     * @mbg.generated
     */
    private String            code;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * P_OBJ_ENUM_VALUE.VALUE
     *
     * @mbg.generated
     */
    private String            value;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * P_OBJ_ENUM_VALUE.P_OBJ_ENUM_GID
     *
     * @return the value of P_OBJ_ENUM_VALUE.P_OBJ_ENUM_GID
     * @mbg.generated
     */
    public String getpObjEnumGid() {
        return pObjEnumGid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * P_OBJ_ENUM_VALUE.P_OBJ_ENUM_GID
     *
     * @param pObjEnumGid the value for P_OBJ_ENUM_VALUE.P_OBJ_ENUM_GID
     * @mbg.generated
     */
    public void setpObjEnumGid(String pObjEnumGid) {
        this.pObjEnumGid = pObjEnumGid == null ? null : pObjEnumGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * P_OBJ_ENUM_VALUE.CODE
     *
     * @return the value of P_OBJ_ENUM_VALUE.CODE
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * P_OBJ_ENUM_VALUE.CODE
     *
     * @param code the value for P_OBJ_ENUM_VALUE.CODE
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * P_OBJ_ENUM_VALUE.VALUE
     *
     * @return the value of P_OBJ_ENUM_VALUE.VALUE
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * P_OBJ_ENUM_VALUE.VALUE
     *
     * @param value the value for P_OBJ_ENUM_VALUE.VALUE
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PObjEnumValue other = (PObjEnumValue) that;
        return (this.getGid() == null ? other.getGid() == null : this.getGid().equals(other.getGid()))
               && (this.getpObjEnumGid() == null ? other.getpObjEnumGid() == null : this.getpObjEnumGid().equals(other.getpObjEnumGid()))
               && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
               && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()))
               && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
               && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
               && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
               && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
               && (this.getActive() == null ? other.getActive() == null : this.getActive().equals(other.getActive()))
               && (this.getDelete() == null ? other.getDelete() == null : this.getDelete().equals(other.getDelete()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGid() == null) ? 0 : getGid().hashCode());
        result = prime * result + ((getpObjEnumGid() == null) ? 0 : getpObjEnumGid().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getActive() == null) ? 0 : getActive().hashCode());
        result = prime * result + ((getDelete() == null) ? 0 : getDelete().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_ENUM_VALUE
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pObjEnumGid=").append(pObjEnumGid);
        sb.append(", code=").append(code);
        sb.append(", value=").append(value);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
