package com.neusoft.designer.service.domain;

import java.io.Serializable;

import com.neusoft.core.dao.GenDO;

public class PObjLayout extends GenDO implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * P_OBJ_LAYOUT.P_OBJ_OBJECT_GID
     *
     * @mbg.generated
     */
    private String            pObjObjectGid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * P_OBJ_LAYOUT.LAYOUT_NAME
     *
     * @mbg.generated
     */
    private String            layoutName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * P_OBJ_LAYOUT.LAYOUT_TYPE
     *
     * @mbg.generated
     */
    private Short             layoutType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * P_OBJ_LAYOUT.IS_DEFAULT
     *
     * @mbg.generated
     */
    private Boolean           df;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column P_OBJ_LAYOUT.FIELDS
     *
     * @mbg.generated
     */
    private String            fields;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * P_OBJ_LAYOUT.JSONDATA
     *
     * @mbg.generated
     */
    private String            jsondata;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * P_OBJ_LAYOUT.P_OBJ_OBJECT_GID
     *
     * @return the value of P_OBJ_LAYOUT.P_OBJ_OBJECT_GID
     * @mbg.generated
     */
    public String getpObjObjectGid() {
        return pObjObjectGid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * P_OBJ_LAYOUT.P_OBJ_OBJECT_GID
     *
     * @param pObjObjectGid the value for P_OBJ_LAYOUT.P_OBJ_OBJECT_GID
     * @mbg.generated
     */
    public void setpObjObjectGid(String pObjObjectGid) {
        this.pObjObjectGid = pObjObjectGid == null ? null : pObjObjectGid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * P_OBJ_LAYOUT.LAYOUT_NAME
     *
     * @return the value of P_OBJ_LAYOUT.LAYOUT_NAME
     * @mbg.generated
     */
    public String getLayoutName() {
        return layoutName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * P_OBJ_LAYOUT.LAYOUT_NAME
     *
     * @param layoutName the value for P_OBJ_LAYOUT.LAYOUT_NAME
     * @mbg.generated
     */
    public void setLayoutName(String layoutName) {
        this.layoutName = layoutName == null ? null : layoutName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * P_OBJ_LAYOUT.LAYOUT_TYPE
     *
     * @return the value of P_OBJ_LAYOUT.LAYOUT_TYPE
     * @mbg.generated
     */
    public Short getLayoutType() {
        return layoutType;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * P_OBJ_LAYOUT.LAYOUT_TYPE
     *
     * @param layoutType the value for P_OBJ_LAYOUT.LAYOUT_TYPE
     * @mbg.generated
     */
    public void setLayoutType(Short layoutType) {
        this.layoutType = layoutType;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * P_OBJ_LAYOUT.IS_DEFAULT
     *
     * @return the value of P_OBJ_LAYOUT.IS_DEFAULT
     * @mbg.generated
     */
    public Boolean getDf() {
        return df;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * P_OBJ_LAYOUT.IS_DEFAULT
     *
     * @param df the value for P_OBJ_LAYOUT.IS_DEFAULT
     * @mbg.generated
     */
    public void setDf(Boolean df) {
        this.df = df;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * P_OBJ_LAYOUT.FIELDS
     *
     * @return the value of P_OBJ_LAYOUT.FIELDS
     * @mbg.generated
     */
    public String getFields() {
        return fields;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * P_OBJ_LAYOUT.FIELDS
     *
     * @param fields the value for P_OBJ_LAYOUT.FIELDS
     * @mbg.generated
     */
    public void setFields(String fields) {
        this.fields = fields == null ? null : fields.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * P_OBJ_LAYOUT.JSONDATA
     *
     * @return the value of P_OBJ_LAYOUT.JSONDATA
     * @mbg.generated
     */
    public String getJsondata() {
        return jsondata;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * P_OBJ_LAYOUT.JSONDATA
     *
     * @param jsondata the value for P_OBJ_LAYOUT.JSONDATA
     * @mbg.generated
     */
    public void setJsondata(String jsondata) {
        this.jsondata = jsondata == null ? null : jsondata.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PObjLayout other = (PObjLayout) that;
        return (this.getGid() == null ? other.getGid() == null : this.getGid().equals(other.getGid()))
               && (this.getpObjObjectGid() == null ? other.getpObjObjectGid() == null : this.getpObjObjectGid().equals(other.getpObjObjectGid()))
               && (this.getLayoutName() == null ? other.getLayoutName() == null : this.getLayoutName().equals(other.getLayoutName()))
               && (this.getLayoutType() == null ? other.getLayoutType() == null : this.getLayoutType().equals(other.getLayoutType()))
               && (this.getDf() == null ? other.getDf() == null : this.getDf().equals(other.getDf()))
               && (this.getFields() == null ? other.getFields() == null : this.getFields().equals(other.getFields()))
               && (this.getJsondata() == null ? other.getJsondata() == null : this.getJsondata().equals(other.getJsondata()))
               && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
               && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
               && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
               && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
               && (this.getActive() == null ? other.getActive() == null : this.getActive().equals(other.getActive()))
               && (this.getDelete() == null ? other.getDelete() == null : this.getDelete().equals(other.getDelete()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGid() == null) ? 0 : getGid().hashCode());
        result = prime * result + ((getpObjObjectGid() == null) ? 0 : getpObjObjectGid().hashCode());
        result = prime * result + ((getLayoutName() == null) ? 0 : getLayoutName().hashCode());
        result = prime * result + ((getLayoutType() == null) ? 0 : getLayoutType().hashCode());
        result = prime * result + ((getDf() == null) ? 0 : getDf().hashCode());
        result = prime * result + ((getFields() == null) ? 0 : getFields().hashCode());
        result = prime * result + ((getJsondata() == null) ? 0 : getJsondata().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getActive() == null) ? 0 : getActive().hashCode());
        result = prime * result + ((getDelete() == null) ? 0 : getDelete().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table P_OBJ_LAYOUT
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pObjObjectGid=").append(pObjObjectGid);
        sb.append(", layoutName=").append(layoutName);
        sb.append(", layoutType=").append(layoutType);
        sb.append(", df=").append(df);
        sb.append(", fields=").append(fields);
        sb.append(", jsondata=").append(jsondata);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
